"""
generate_bias_configs.py -- take a reference config .toml (like your
input_polar.toml) and write out one copy per bias-potential profile from
bias_profiles.py, with [bias].ring_volts replaced by that profile evaluated
at the reference file's own ring_radii. Everything else in the file --
comments, formatting, every other section -- is left untouched.

By default each generated file's [output].outdir is rewritten to
    <everything up through .../plasma_sim_runs from the reference file>/<outdir's basename>/<profile name>
e.g. if the reference's outdir is ".../plasma_sim_runs/polar_200f_.../" and
you run this with <outdir>=scan/bias_profile_scan_configs, each generated
config's outdir becomes ".../plasma_sim_runs/bias_profile_scan_configs/linear_decreasing"
-- so the pscratch location is tied to the name of the scan you're generating
(the <outdir> argument), not whatever experiment name happened to be baked
into the reference file, and every profile still gets its own subdirectory so
running them all together (run_files.sh / run_multinode.sh) doesn't have one
profile's run overwrite another's output. Use --no-adjust-outdir to keep
outdir exactly as written in the reference file.

Usage:
    python scan/generate_bias_configs.py <reference.toml> <outdir>
    python scan/generate_bias_configs.py <reference.toml> <outdir> --profiles linear_decreasing,hollow_center
    python scan/generate_bias_configs.py --list
"""
from __future__ import annotations

import argparse
import csv
import os
import re
import sys
import tomllib
from datetime import date

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from bias_profiles import PROFILES  # noqa: E402

RING_VOLTS_RE = re.compile(r'(?m)^(?P<prefix>\s*ring_volts\s*=\s*)\[[^\]]*\]')
OUTDIR_RE = re.compile(r'(?m)^(?P<prefix>\s*outdir\s*=\s*)"(?P<val>[^"]*)"')


def to_u(r, r_min, r_max):
    return (r - r_min) / (r_max - r_min)


def format_volts(vals, precision):
    return "[" + ", ".join(f"{v:.{precision}f}" for v in vals) + "]"


MARKER = "plasma_sim_runs"


def build_config_text(ref_text, ref_name, profile_name, profile_desc, volts, precision,
                       adjust_outdir, config_dir_name):
    volts_str = format_volts(volts, precision)

    new_text, n = RING_VOLTS_RE.subn(
        lambda m: m.group("prefix") + volts_str, ref_text, count=1)
    if n == 0:
        raise ValueError(
            f"could not find an (uncommented) 'ring_volts = [...]' line in {ref_name}")

    if adjust_outdir:
        def _outdir_repl(m):
            old_val = m.group("val").rstrip("/")
            idx = old_val.find(MARKER)
            if idx == -1:
                # couldn't find plasma_sim_runs in the reference outdir -- fall back to
                # just nesting config_dir_name/profile_name under whatever was there
                print(f"  WARNING: '{MARKER}' not found in outdir '{old_val}' for {ref_name}, "
                      f"appending {config_dir_name}/{profile_name} to it instead", file=sys.stderr)
                base = old_val
            else:
                base = old_val[: idx + len(MARKER)]
            new_val = f"{base}/{config_dir_name}/{profile_name}"
            return f'{m.group("prefix")}"{new_val}"'
        new_text, n_out = OUTDIR_RE.subn(_outdir_repl, new_text, count=1)
        if n_out == 0:
            print(f"  WARNING: no 'outdir = \"...\"' line found in {ref_name}, "
                  f"leaving output dir untouched for {profile_name}", file=sys.stderr)

    header = (
        "# ---------------------------------------------------------------------\n"
        f"# AUTO-GENERATED by generate_bias_configs.py on {date.today().isoformat()}\n"
        f"# Reference:  {ref_name}\n"
        f"# Profile:    {profile_name} -- {profile_desc}\n"
        "# Only [bias].ring_volts"
        + (" and [output].outdir" if adjust_outdir else "")
        + " were changed below; everything else is copied from the reference.\n"
        "# ---------------------------------------------------------------------\n"
    )
    return header + new_text


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("reference", nargs="?", help="reference config .toml to base all outputs on")
    ap.add_argument("outdir", nargs="?", help="directory to write the generated .toml files into")
    ap.add_argument("--profiles", default=None,
                     help="comma-separated list of profile names to generate (default: all 34)")
    ap.add_argument("--precision", type=int, default=4,
                     help="decimal places for the generated ring_volts (default: 4)")
    ap.add_argument("--no-adjust-outdir", action="store_true",
                     help="don't append the profile name to [output].outdir")
    ap.add_argument("--list", action="store_true",
                     help="print available profile names and exit")
    args = ap.parse_args()

    if args.list:
        for name, desc, _ in PROFILES:
            print(f"{name:30s} {desc}")
        return

    if not args.reference or not args.outdir:
        ap.error("reference and outdir are required unless --list is given")

    with open(args.reference, "rb") as fh:
        ref_dict = tomllib.load(fh)
    ref_text = open(args.reference, "r").read()
    ref_name = os.path.basename(args.reference)
    ref_stem = os.path.splitext(ref_name)[0]

    try:
        ring_radii = ref_dict["bias"]["ring_radii"]
    except KeyError:
        raise SystemExit(f"ERROR: {args.reference} has no [bias].ring_radii to evaluate profiles at")

    r_min, r_max = min(ring_radii), max(ring_radii)

    if args.profiles:
        wanted = set(n.strip() for n in args.profiles.split(","))
        selected = [p for p in PROFILES if p[0] in wanted]
        missing = wanted - {p[0] for p in selected}
        if missing:
            raise SystemExit(f"ERROR: unknown profile name(s): {sorted(missing)} "
                              f"(use --list to see available names)")
    else:
        selected = PROFILES

    os.makedirs(args.outdir, exist_ok=True)
    adjust_outdir = not args.no_adjust_outdir
    config_dir_name = os.path.basename(os.path.normpath(args.outdir))

    manifest_rows = []
    for name, desc, f in selected:
        volts = [round(float(f(to_u(r, r_min, r_max))), args.precision) for r in ring_radii]
        text = build_config_text(ref_text, ref_name, name, desc, volts, args.precision,
                                  adjust_outdir, config_dir_name)
        out_name = f"{ref_stem}_{name}.toml"
        out_path = os.path.join(args.outdir, out_name)
        with open(out_path, "w") as fh:
            fh.write(text)
        manifest_rows.append({
            "profile": name, "description": desc, "config_file": out_name,
            "ring_radii": ring_radii, "ring_volts": volts,
        })
        print(f"wrote {out_path}")

    manifest_path = os.path.join(args.outdir, "manifest.csv")
    with open(manifest_path, "w", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=["profile", "description", "config_file",
                                                 "ring_radii", "ring_volts"])
        writer.writeheader()
        writer.writerows(manifest_rows)

    print(f"\n{len(selected)} config(s) written to {args.outdir}")
    print(f"manifest: {manifest_path}")


if __name__ == "__main__":
    main()