"""
generate_bo_config.py -- write a single run config for one Bayesian-optimization
trial: fixed ring_radii (5 equally spaced points from 0.1 to limiter_radius) and
a candidate ring_volts vector (whatever the optimizer just asked for), spliced
into the reference.toml used for this campaign. Everything else in the
reference file -- U, H, kappa, nu4, nu5, nu4p, nu5p, limiter settings, initial
conditions, time stepping -- is left untouched (same text-preserving
regex-substitution approach as generate_bias_configs.py, just substituting
ring_radii too, since the reference file's own ring_radii don't match the
5-point BO scheme).

Usage (as a library, from the driver script):
    from generate_bo_config import build_trial_config
    text = build_trial_config(ref_text, ring_radii, ring_volts, outdir, trial_id)

Usage (standalone, for testing):
    python generate_bo_config.py <reference.toml> <out.toml> <outdir> \
        --radii 0.1,0.45,0.8,1.15,1.5 --volts 1.2,-0.5,3.1,0.0,-2.7
"""
from __future__ import annotations

import argparse
import re
from datetime import date

RING_RADII_RE = re.compile(r'(?m)^(?P<prefix>\s*ring_radii\s*=\s*)\[[^\]]*\]')
RING_VOLTS_RE = re.compile(r'(?m)^(?P<prefix>\s*ring_volts\s*=\s*)\[[^\]]*\]')
OUTDIR_RE = re.compile(r'(?m)^(?P<prefix>\s*outdir\s*=\s*)"(?P<val>[^"]*)"')


def format_list(vals, precision):
    return "[" + ", ".join(f"{v:.{precision}f}" for v in vals) + "]"


def build_trial_config(ref_text, ring_radii, ring_volts, outdir, trial_id,
                        precision=4, ref_name="reference.toml"):
    """Return the full text of a trial config: ref_text with [bias].ring_radii,
    [bias].ring_volts, and [output].outdir replaced. Raises ValueError if any
    of those three lines can't be found (uncommented) in ref_text."""
    radii_str = format_list(ring_radii, precision)
    volts_str = format_list(ring_volts, precision)

    new_text, n = RING_RADII_RE.subn(
        lambda m: m.group("prefix") + radii_str, ref_text, count=1)
    if n == 0:
        raise ValueError(f"could not find an (uncommented) 'ring_radii = [...]' line in {ref_name}")

    new_text, n = RING_VOLTS_RE.subn(
        lambda m: m.group("prefix") + volts_str, new_text, count=1)
    if n == 0:
        raise ValueError(f"could not find an (uncommented) 'ring_volts = [...]' line in {ref_name}")

    def _outdir_repl(m):
        return f'{m.group("prefix")}"{outdir}"'
    new_text, n_out = OUTDIR_RE.subn(_outdir_repl, new_text, count=1)
    if n_out == 0:
        raise ValueError(f"could not find an (uncommented) 'outdir = \"...\"' line in {ref_name}")

    header = (
        "# ---------------------------------------------------------------------\n"
        f"# AUTO-GENERATED by generate_bo_config.py on {date.today().isoformat()}\n"
        f"# Reference:  {ref_name}\n"
        f"# BO trial:   {trial_id}\n"
        "# Only [bias].ring_radii, [bias].ring_volts, and [output].outdir were\n"
        "# changed below; every physics parameter is copied from the reference.\n"
        "# ---------------------------------------------------------------------\n"
    )
    return header + new_text


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("reference", help="reference config .toml for this BO campaign")
    ap.add_argument("out", help="path to write the generated trial .toml to")
    ap.add_argument("outdir", help="pscratch output directory for this trial's run")
    ap.add_argument("--radii", required=True, help="comma-separated ring_radii")
    ap.add_argument("--volts", required=True, help="comma-separated ring_volts")
    ap.add_argument("--trial-id", default="manual-test")
    ap.add_argument("--precision", type=int, default=4)
    args = ap.parse_args()

    ring_radii = [float(x) for x in args.radii.split(",")]
    ring_volts = [float(x) for x in args.volts.split(",")]

    ref_text = open(args.reference, "r").read()
    text = build_trial_config(ref_text, ring_radii, ring_volts, args.outdir,
                               args.trial_id, args.precision, args.reference)
    with open(args.out, "w") as fh:
        fh.write(text)
    print(f"wrote {args.out}  (outdir={args.outdir})")


if __name__ == "__main__":
    main()